name: JSON Schema Check
description:
  Check a given JSON schema file in the repository for being valid and for
  differences to the previous release.
author: Thomas Jejkal
branding:
  icon: check-square
  color: gray-dark

inputs:
  schemaPath:
    description: 'Relative path of the schema file to check'
    required: true
  schemaVersion:
    description:
      'JSON schema version to use for validating the schema. Available options
      are draft-07 (default), 2019, and 2020.'
    required: false
    default: 'draft-07'
  validate:
    description: 'Validate the schema itself against the JSON specification'
    required: false
    default: 'true'
  createDiff:
    description:
      'Tries to create a diff to the previous release. If none exist, this will
      be skipped.'
    required: false
    default: 'true'
  token:
    description: 'GitHub token for reading previous tags.'
    required: false
  previousVersion:
    description: 'The previous version/tag name to apply the diff against.'
    required: false
outputs:
  message:
    description: 'The schema check output as markdown message.'

runs:
  using: node20
  main: dist/index.js
