name: JSON Schema Check
description:
  Check a given JSON schema file in the repository for being valid and for
  differences to the previous release.
author: Thomas Jejkal
branding:
  icon: check-square
  color: gray-dark

inputs:
  schemaPath:
    description: 'Relative path of the schema file to check'
    required: true
  validate:
    description: 'Validate the schema itself against the JSON specification'
    required: false
    default: 'true'
  createDiff:
    description:
      'Tries to create a diff to the previous release. If none exist, this will
      be skipped.'
    required: false
    default: 'true'
  token:
    description: 'GitHub token for reading previous tags.'
    required: false
outputs:
  message:
    description: 'The schema check output as markdown message.'

runs:
  using: node20
  main: dist/index.js
